### ISSUE TITLE
Rateeq and OBE objects fail to initialize

### ISSUE THREAD

**Issue by bdalfavero** [JQIamo/pylcp#64]
When I attempt to initialize a `rateeq ` or `obe`  object, there is an error. If you look at the `__init__()` method, it takes the parameter `hamitlonian` instead of `hamiltonian`.

**Comment by dsbarker** [comment]
Good catch! We'll fix this in the next bug fix.

The code is still usable since the 'hamitlonian' is a positional argument. Just pass your Hamiltonian to the governing equation without the keyword:
```
obe = pylcp.obe(laserBeams, magField, Hamiltonian)
```

**Comment by dsbarker** [comment]
Fixed the typo with [8e7dca7](https://github.com/JQIamo/pylcp/commit/8e7dca74d229cf25ba72918989628e07e2c702f8).
