### ISSUE TITLE
How to connect the magnetic field gradient B’ (G/cm) with the alpha in pylcp?

### ISSUE THREAD

**Issue by xuanzhuedmund** [JQIamo/pylcp#67]
Hello, Could you tell me how to connect the magnetic field gradient B’ (G/cm) with the alpha in pylcp?

**Comment by dsbarker** [comment]
You can find this information in the "Choose the Units" section of the [F=0 to F=1 MOT](https://python-laser-cooling-physics.readthedocs.io/en/latest/examples/MOTs/00_F0_to_F1_1D_MOT_forces.html) example on readthedocs.

As this question is not a bug or feature request, it would be better for you to ask future similar questions on our googlegroup: [https://groups.google.com/g/pylcp/](https://groups.google.com/g/pylcp/).
